export const CITIES_ENUM = [
  "Belo Horizonte",
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Curitiba",
  "Manaus",
  "Recife",
  "Porto Alegre",
  "Lisboa",
  "Madri",
  "Paris",
  "Londres",
  "Berlim",
  "Roma",
  "Amsterdã",
  "Barcelona",
  "Bruxelas",
  "Milão",
  "Nova York",
  "Los Angeles",
  "Toronto",
  "Vancouver",
  "Montreal",
  "Chicago",
  "Miami",
  "Washington, D.C.",
  "Boston",
  "Dallas",
];

export const weatherTranslations: { [key: string]: string } = {
  Clear: "Céu limpo",
  Sunny: "Ensolarado",
  "Partly cloudy": "Parcialmente nublado",
  Cloudy: "Nublado",
  Overcast: "Encoberto",
  Mist: "Névoa",
  "Patchy rain possible": "Possibilidade de chuva isolada",
  "Patchy snow possible": "Possibilidade de neve isolada",
  "Patchy sleet possible": "Possibilidade de chuva congelante isolada",
  "Patchy freezing drizzle possible":
    "Possibilidade de garoa congelante isolada",
  "Thundery outbreaks possible": "Possibilidade de tempestades",
  "Blowing snow": "Neve soprada pelo vento",
  Blizzard: "Nevasca",
  Fog: "Nevoeiro",
  "Freezing fog": "Nevoeiro congelante",
  "Patchy light drizzle": "Chuvisco fraco isolado",
  "Light drizzle": "Chuvisco fraco",
  "Freezing drizzle": "Garoa congelante",
  "Heavy freezing drizzle": "Garoa congelante intensa",
  "Patchy light rain": "Chuva fraca isolada",
  "Light rain": "Chuva fraca",
  "Moderate rain at times": "Chuva moderada ocasionalmente",
  "Moderate rain": "Chuva moderada",
  "Heavy rain at times": "Chuva forte ocasionalmente",
  "Heavy rain": "Chuva forte",
  "Light freezing rain": "Chuva congelante fraca",
  "Moderate or heavy freezing rain": "Chuva congelante moderada ou forte",
  "Light sleet": "Chuva congelante fraca",
  "Moderate or heavy sleet": "Chuva congelante moderada ou forte",
  "Patchy light snow": "Neve fraca isolada",
  "Light snow": "Neve fraca",
  "Patchy moderate snow": "Neve moderada isolada",
  "Moderate snow": "Neve moderada",
  "Patchy heavy snow": "Neve forte isolada",
  "Heavy snow": "Neve forte",
  "Ice pellets": "Granizo",
  "Light rain shower": "Pancada de chuva fraca",
  "Moderate or heavy rain shower": "Pancada de chuva moderada ou forte",
  "Torrential rain shower": "Chuva torrencial",
  "Light sleet showers": "Pancadas fracas de chuva congelante",
  "Moderate or heavy sleet showers":
    "Pancadas moderadas ou fortes de chuva congelante",
  "Light snow showers": "Pancadas fracas de neve",
  "Moderate or heavy snow showers": "Pancadas moderadas ou fortes de neve",
  "Light showers of ice pellets": "Pancadas fracas de granizo",
  "Moderate or heavy showers of ice pellets":
    "Pancadas moderadas ou fortes de granizo",
  "Patchy light rain with thunder": "Chuva fraca isolada com trovões",
  "Moderate or heavy rain with thunder": "Chuva moderada ou forte com trovões",
  "Patchy light snow with thunder": "Neve fraca isolada com trovões",
  "Moderate or heavy snow with thunder": "Neve moderada ou forte com trovões",
};
